{
  "id": "12343566",
  "name": "6.6.6",
  "description": "Bugfix release after 6.6.5",
  "date": "2019-04-05",
  "version": "6.6.6",
  "module": "",
  "lastUpdated": 1633092785558,
  "type": "release",
  "_links": {
    "self": {
      "href": "https://apis.danklco.com/apache-release-info/LUCENE/12343566"
    },
    "jira": {
      "href": "https://issues.apache.org/jira/browse/LUCENE/fixforversion/12343566"
    },
    "project": {
      "href": "https://apis.danklco.com/apache-release-info/LUCENE"
    }
  },
  "releaseNotes": "Release Notes - Lucene - Core - Version 6.6.6",
  "_embedded": {
    "issues": [
      {
        "issue": "LUCENE-8444",
        "title": "Geo3D Test Failure: Test Point is Contained by shape but outside the XYZBounds",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/LUCENE/12343566"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/LUCENE-8444"
          }
        }
      },
      {
        "issue": "LUCENE-8445",
        "title": "RandomGeoPolygonTest.testCompareBigPolygons() failure",
        "type": "Bug",
        "_links": {
          "release": {
            "href": "https://apis.danklco.com/apache-release-info/LUCENE/12343566"
          },
          "jira": {
            "href": "https://issues.apache.org/jira/browse/LUCENE-8445"
          }
        }
      }
    ]
  }
}